import { lazy } from 'react';

export const TOOL_COMPONENTS = {
  'uuid-generator': lazy(() => import('@/components/tools/UuidGenerator').then((m) => ({ default: m.UuidGenerator }))),
  'base64-encode': lazy(() => import('@/components/tools/Base64Encoder').then((m) => ({ default: m.Base64Encoder }))),
  'password-generator': lazy(() => import('@/components/tools/PasswordGenerator').then((m) => ({ default: m.PasswordGenerator }))),
  'json-formatter': lazy(() => import('@/components/tools/JsonFormatter').then((m) => ({ default: m.JsonFormatter }))),
  'slug-generator': lazy(() => import('@/components/tools/SlugGenerator').then((m) => ({ default: m.SlugGenerator }))),
  'hash-generator': lazy(() => import('@/components/tools/HashGenerator').then((m) => ({ default: m.HashGenerator }))),
  'color-converter': lazy(() => import('@/components/tools/ColorConverter').then((m) => ({ default: m.ColorConverter }))),
  'lorem-ipsum': lazy(() => import('@/components/tools/LoremIpsumGenerator').then((m) => ({ default: m.LoremIpsumGenerator }))),
  'word-counter': lazy(() => import('@/components/tools/WordCounter').then((m) => ({ default: m.WordCounter }))),
  'character-counter': lazy(() => import('@/components/tools/CharacterCounter').then((m) => ({ default: m.CharacterCounter }))),
  'case-converter': lazy(() => import('@/components/tools/CaseConverter').then((m) => ({ default: m.CaseConverter }))),
  'url-encoder-decoder': lazy(() => import('@/components/tools/UrlEncoderDecoder').then((m) => ({ default: m.UrlEncoderDecoder }))),
  'html-entity-encoder-decoder': lazy(() => import('@/components/tools/HtmlEntityEncoderDecoder').then((m) => ({ default: m.HtmlEntityEncoderDecoder }))),
  'timestamp-converter': lazy(() => import('@/components/tools/TimestampConverter').then((m) => ({ default: m.TimestampConverter }))),
  'percentage-calculator': lazy(() => import('@/components/tools/PercentageCalculator').then((m) => ({ default: m.PercentageCalculator }))),
  'text-diff-checker': lazy(() => import('@/components/tools/TextDiffChecker').then((m) => ({ default: m.TextDiffChecker }))),
  'markdown-previewer': lazy(() => import('@/components/tools/MarkdownPreviewer').then((m) => ({ default: m.MarkdownPreviewer }))),
  'json-to-csv': lazy(() => import('@/components/tools/JsonToCsvConverter').then((m) => ({ default: m.JsonToCsvConverter }))),
  'json-validator': lazy(() => import('@/components/tools/JsonValidator').then((m) => ({ default: m.JsonValidator }))),
  'json-minifier': lazy(() => import('@/components/tools/JsonMinifier').then((m) => ({ default: m.JsonMinifier }))),
  'csv-to-json': lazy(() => import('@/components/tools/CsvToJsonConverter').then((m) => ({ default: m.CsvToJsonConverter }))),
  'url-parser': lazy(() => import('@/components/tools/UrlParser').then((m) => ({ default: m.UrlParser }))),
  'jwt-decoder': lazy(() => import('@/components/tools/JwtDecoder').then((m) => ({ default: m.JwtDecoder }))),
  'regex-tester': lazy(() => import('@/components/tools/RegexTester').then((m) => ({ default: m.RegexTester }))),
  'html-minifier': lazy(() => import('@/components/tools/HtmlMinifier').then((m) => ({ default: m.HtmlMinifier }))),
  'css-minifier': lazy(() => import('@/components/tools/CssMinifier').then((m) => ({ default: m.CssMinifier }))),
  'javascript-minifier': lazy(() => import('@/components/tools/JavaScriptMinifier').then((m) => ({ default: m.JavaScriptMinifier }))),
  'query-string-builder': lazy(() => import('@/components/tools/QueryStringBuilder').then((m) => ({ default: m.QueryStringBuilder }))),
  'length-converter': lazy(() => import('@/components/tools/LengthConverter').then((m) => ({ default: m.LengthConverter }))),
  'weight-converter': lazy(() => import('@/components/tools/WeightConverter').then((m) => ({ default: m.WeightConverter }))),
  'temperature-converter': lazy(() => import('@/components/tools/TemperatureConverter').then((m) => ({ default: m.TemperatureConverter }))),
  'area-converter': lazy(() => import('@/components/tools/AreaConverter').then((m) => ({ default: m.AreaConverter }))),
  'volume-converter': lazy(() => import('@/components/tools/VolumeConverter').then((m) => ({ default: m.VolumeConverter }))),
  'speed-converter': lazy(() => import('@/components/tools/SpeedConverter').then((m) => ({ default: m.SpeedConverter }))),
  'time-converter': lazy(() => import('@/components/tools/TimeConverter').then((m) => ({ default: m.TimeConverter }))),
  'data-storage-converter': lazy(() => import('@/components/tools/DataStorageConverter').then((m) => ({ default: m.DataStorageConverter }))),
  'angle-converter': lazy(() => import('@/components/tools/AngleConverter').then((m) => ({ default: m.AngleConverter }))),
  'fuel-consumption-converter': lazy(() => import('@/components/tools/FuelConsumptionConverter').then((m) => ({ default: m.FuelConsumptionConverter }))),
  'discount-calculator': lazy(() => import('@/components/tools/DiscountCalculator').then((m) => ({ default: m.DiscountCalculator }))),
  'vat-calculator': lazy(() => import('@/components/tools/VatCalculator').then((m) => ({ default: m.VatCalculator }))),
  'profit-margin-calculator': lazy(() => import('@/components/tools/ProfitMarginCalculator').then((m) => ({ default: m.ProfitMarginCalculator }))),
  'rule-of-three-calculator': lazy(() => import('@/components/tools/RuleOfThreeCalculator').then((m) => ({ default: m.RuleOfThreeCalculator }))),
  'average-calculator': lazy(() => import('@/components/tools/AverageCalculator').then((m) => ({ default: m.AverageCalculator }))),
  'age-calculator': lazy(() => import('@/components/tools/AgeCalculator').then((m) => ({ default: m.AgeCalculator }))),
  'date-difference-calculator': lazy(() => import('@/components/tools/DateDifferenceCalculator').then((m) => ({ default: m.DateDifferenceCalculator }))),
  'bmi-calculator': lazy(() => import('@/components/tools/BmiCalculator').then((m) => ({ default: m.BmiCalculator }))),
  'loan-calculator': lazy(() => import('@/components/tools/LoanCalculator').then((m) => ({ default: m.LoanCalculator }))),
  'tip-calculator': lazy(() => import('@/components/tools/TipCalculator').then((m) => ({ default: m.TipCalculator }))),
} as const;

export type ToolSlug = keyof typeof TOOL_COMPONENTS;

export function hasToolComponent(slug: string): slug is ToolSlug {
  return slug in TOOL_COMPONENTS;
}
